-- AlterTable
ALTER TABLE "short" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ALTER COLUMN "topic" DROP NOT NULL,
ALTER COLUMN "timeStamp" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "short_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "short_id_seq";
